import path from 'path'
import esbuild from 'esbuild'
import process from 'process'
import { builtinModules } from 'module'
import fs from 'fs'

const nodeBuiltins = [...builtinModules, ...builtinModules.map((mod) => `node:${mod}`)]

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

const copyFilesPlugin = {
  name: 'copy-files-plugin',
  setup(build) {
    build.onEnd(() => {
      const outDir = 'output/obsidian-aider'
      if (!fs.existsSync(outDir)) {
        fs.mkdirSync(outDir, { recursive: true })
      }
      if (fs.existsSync('main.js')) {
        fs.copyFileSync('main.js', path.join(outDir, 'main.js'))
      }
      if (fs.existsSync('manifest.json')) {
        fs.copyFileSync('manifest.json', path.join(outDir, 'manifest.json'))
      }
      if (fs.existsSync('styles.css')) {
        fs.copyFileSync('styles.css', path.join(outDir, 'styles.css'))
      }
      console.log('Copied main.js, manifest.json and styles.css to output/obsidian-aider/')
    })
  }
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    '@lexical/clipboard/clipboard',
    ...nodeBuiltins,
  ],
  format: 'cjs',
  define: {
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
  },
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  plugins: [copyFilesPlugin],
})

if (prod) {
  await context.rebuild()
  process.exit(0)
} else {
  await context.watch()
}
